wandb:
  entity: "marcelo-lemos"
  project: "deep-frozen-lake"

dqn:
  learning_rate: 1e-2
  gamma: 0.9
  epsilon: 1.0
  epsilon_decay: 0.999
  replay_buffer_size: 4096
  sync_rate: 5
  max_steps: 5000
  batch_size: 256
