wandb:
  entity: "marcelo-lemos"
  project: "deep-frozen-lake"

dqn:
  learning_rate: 1e-3
  gamma: 0.99
  epsilon: 1
  epsilon_decay: 0.99993
  replay_buffer_size: 4096
  sync_rate: 50
  max_steps: 30000
  batch_size: 256
